### ISSUE TITLE
Неточности вёрстки

### ISSUE THREAD

**Issue by Everrest1** [timon0596/toxin-UIkit#25]
Ui-kit тоже верстаем по pixel-perfect

**Comment by Everrest1** [comment]
Кнопка "Применить" как будто ничего не делает

![image](https://user-images.githubusercontent.com/43137324/93741041-c09bfc80-fbfc-11ea-9dd4-e915bd535dbf.png)

**Comment by Everrest1** [comment]
Второй Dropdown перекрывает первый

![image](https://user-images.githubusercontent.com/43137324/93741173-f3de8b80-fbfc-11ea-9307-9ab2f4ae12e9.png)

**Comment by Everrest1** [comment]
Анимация с каким-то "лагом"

![Peek 2020-09-21 11-25](https://user-images.githubusercontent.com/43137324/93741287-2ee0bf00-fbfd-11ea-9de2-1921e7f1574d.gif)

**Comment by Everrest1** [comment]
Лучше убрать возможность брать выделение с интерактивных элементов

![image](https://user-images.githubusercontent.com/43137324/93741462-84b56700-fbfd-11ea-9ed5-6571d925bb26.png)

**Comment by Everrest1** [comment]
Выглядит поломано

![image](https://user-images.githubusercontent.com/43137324/93741859-36549800-fbfe-11ea-8ede-6a48fe35f3ba.png)

**Comment by Everrest1** [comment]
Размер календаря не соответствует своему инпуту

![image](https://user-images.githubusercontent.com/43137324/94289539-e6f9c900-ff69-11ea-82e2-de917db97527.png)

**Comment by Everrest1** [comment]
Размер шрифта, цвет и отступ не соответствуют макету

![image](https://user-images.githubusercontent.com/43137324/94289928-88811a80-ff6a-11ea-972f-64e173c40fbe.png)

**Comment by Hahahayabanan** [comment]
> Анимация с каким-то "лагом"
> 
> ![Peek 2020-09-21 11-25](https://user-images.githubusercontent.com/43137324/93741287-2ee0bf00-fbfd-11ea-9de2-1921e7f1574d.gif)

Скорее всего лаг из-за метода slideToggle

**Comment by Everrest1** [comment]
> Размер календаря не соответствует своему инпуту
> 


Полноразмерный календарь оставить по макету

![image](https://user-images.githubusercontent.com/43137324/94392169-85ec1400-0168-11eb-85f0-9fbd0c8fc5ab.png)

**Comment by Everrest1** [comment]
label чекбокса тоже должен быть кликабельным

![image](https://user-images.githubusercontent.com/43137324/94773390-baf8a080-03cc-11eb-9db9-21ebab74cd7e.png)

**Comment by Everrest1** [comment]
В поле можно ввести дату, но при этом ничего не происходит

![image](https://user-images.githubusercontent.com/43137324/94773481-e8dde500-03cc-11eb-96ef-9fbd18ad0076.png)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/94773514-fb581e80-03cc-11eb-869a-fba4c1971483.png)

**Comment by Everrest1** [comment]
Если будет немного больше лайков, кнопка ломается

![image](https://user-images.githubusercontent.com/43137324/94773601-28a4cc80-03cd-11eb-92f0-27b2e01dd80b.png)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/94773733-702b5880-03cd-11eb-99ba-6a717cff5958.png)

**Comment by Everrest1** [comment]
Если ввести невалидную дату, то календарь ломается и кнопка "Очистить" не сбрасывает в первоначальный вид

![image](https://user-images.githubusercontent.com/43137324/95946190-1a0eda00-0dfd-11eb-98ae-e11e881cf0f3.png)

**Comment by Everrest1** [comment]
После клика на "Применить" и повторного открытия цвет границы инпута остаётся, как без фокуса

![image](https://user-images.githubusercontent.com/43137324/95946351-6d812800-0dfd-11eb-807e-98432f399f85.png)

**Comment by Everrest1** [comment]
placeholder должен быть заглавными буквами, согласно макету

![image](https://user-images.githubusercontent.com/43137324/95946575-e1bbcb80-0dfd-11eb-956c-1377b0c88ff2.png)

![image](https://user-images.githubusercontent.com/43137324/95946593-ed0ef700-0dfd-11eb-94e5-0221a1285d12.png)

**Comment by Everrest1** [comment]
Не хватает подчёркивающей линии

![image](https://user-images.githubusercontent.com/43137324/95946773-4840e980-0dfe-11eb-8081-f47b1ec32a91.png)
![image](https://user-images.githubusercontent.com/43137324/95946787-5262e800-0dfe-11eb-8039-af4fc7ab956c.png)

**Comment by Everrest1** [comment]
Нет разделительной линии перед футером

![image](https://user-images.githubusercontent.com/43137324/95947044-d917c500-0dfe-11eb-8aec-202dc0bc5783.png)

**Comment by Everrest1** [comment]
После нажатия "Применить" остался тот лаг

![Peek 2020-10-26 17-48](https://user-images.githubusercontent.com/43137324/97180459-869db780-17b3-11eb-97de-a28d8b1d7468.gif)

**Comment by Everrest1** [comment]
У инпутов края обрезаны
На скрине снизу dropdown, с ним всё ок

![image](https://user-images.githubusercontent.com/43137324/97180653-c5cc0880-17b3-11eb-8058-d7e7066d1060.png)

**Comment by Everrest1** [comment]
Не на всех страницах нужна разделительная линия

![image](https://user-images.githubusercontent.com/43137324/97181268-8356fb80-17b4-11eb-8418-8af7606e6508.png)

**Comment by Everrest1** [comment]
С хэдером что-то не так

![image](https://user-images.githubusercontent.com/43137324/98635488-84ecfb80-233e-11eb-984f-78498e66647b.png)

**Comment by Everrest1** [comment]
Один инпут меньше остальных
На страницах с китом не хватает логотипа

![image](https://user-images.githubusercontent.com/43137324/99812084-746b2b00-2b5f-11eb-8252-9a8dd146e050.png)
