### ISSUE TITLE
Именование БЭМ

### ISSUE THREAD

**Issue by Everrest1** [timon0596/toxin-UIkit#5]
По стандартам п.1 https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

![image](https://user-images.githubusercontent.com/43137324/87879235-8e063580-c9fa-11ea-8c5a-583e23e2d4ae.png)

**Comment by Everrest1** [comment]
Слова в имени блока отделяются дефисом. Такие сокращения недопустимы

![image](https://user-images.githubusercontent.com/43137324/88621758-53636380-d0b2-11ea-9c96-530de5368b81.png)

**Comment by Everrest1** [comment]
Сейчас у тебя получается элемент будет иметь класс либо `bullet-list`, либо `bullet-lists_modifier-name`, но согласно БЭМ класс должен включать в себя название блока/элемента и затем его модификаторы

![image](https://user-images.githubusercontent.com/43137324/89256167-8c608280-d634-11ea-9b2a-572180c0a0b2.png)

**Comment by Everrest1** [comment]
Здесь можно назвать блок просто `checkbox`
У тебя сейчас получается блок `.checkbox` внутри другого блока `.checkbox-button`
Посмотри по всему проекту, плиз

![image](https://user-images.githubusercontent.com/43137324/89256450-304a2e00-d635-11ea-8023-9451c68445b0.png)

**Comment by Everrest1** [comment]
Тоже самое, если тебе нудно выделить независимую самостоятельную сущность ты выносишь её в блок в отдельную папку, в отдельный файл и используешь, как модификатор, передавая параметры

![image](https://user-images.githubusercontent.com/43137324/89256655-a9e21c00-d635-11ea-96d0-15be85c27e78.png)

**Comment by Everrest1** [comment]
Имя блока не соответствует миксину и классу

![image](https://user-images.githubusercontent.com/43137324/89857703-d1913100-dbad-11ea-8241-eb3e35be4ed0.png)

**Comment by Everrest1** [comment]
Имя файла должно соответствовать имени блока

![image](https://user-images.githubusercontent.com/43137324/89857867-43697a80-dbae-11ea-8df7-b8fca5ba3aab.png)

**Comment by Everrest1** [comment]
Имя блока не соответствует миксину и классу

![image](https://user-images.githubusercontent.com/43137324/89858008-96dbc880-dbae-11ea-97ea-40064bbd9a50.png)

**Comment by Everrest1** [comment]
![image](https://user-images.githubusercontent.com/43137324/89858541-030afc00-dbb0-11ea-9482-9ec7a485e4af.png)

**Comment by Everrest1** [comment]
Заголовки лучше сделать одним блоком, и нужно дать им более осмысленное название, например, `heading`. `i` тоже не говорит о назначении блока, можно назвать `material-icons`

![image](https://user-images.githubusercontent.com/43137324/90309360-10e6b700-def9-11ea-8c99-989aaba99d66.png)

**Comment by Hahahayabanan** [comment]
Имя файла не совпадает с именем блока. В блоке присутствует внутренняя реализация других блоков.
Для более удобного и простого переиспользования блоков мы выносим их в отдельные файлы и оборачиваем миксином

![image](https://user-images.githubusercontent.com/43137324/90309582-e4cc3580-defa-11ea-80af-523872d97940.png)

**Comment by Everrest1** [comment]
Не нужно оставлять тег без класса, даже если для него нет стилей, это добавляет неочевидности, какую роль выполняет в данном блоке

![image](https://user-images.githubusercontent.com/43137324/90597189-9d4aef80-e201-11ea-8e41-48450f295afd.png)
